Changed the implementation of the c_utf8 macro.
The old union-based implementation had a corner case where its use in
certain const expressions would cause an E0716 error.

Although I don't fully understand why the compiler believes there's a
problem, the error seems to occur when the macro is used inside a
slice literal (possibly nested within other structs), and that slice
is used within another const value. Example below:

error[E0716]: temporary value dropped while borrowed
NonEmptySlice::new(&[c_utf8!("sub")]);
--------------------^^^^^^^^^^^^^^^^-
|                   |               |
|                   |               temporary value is freed at the end of this statement
|                   creates a temporary value which is freed while still in use
using this value as a constant requires that borrow lasts for `'static`

The new implementation doesn't rely on creating a temporary union
value, so it doesn't trigger the error.